In [1]:
import pandas as pd

In [6]:
data={"name":["a","b","c"], "age":[20,40,30],"score":[1,2,3]}
df=pd.DataFrame(data)
df

  name  age  score
0    a   20      1
1    b   40      2
2    c   30      3

In [7]:
df['name']

0    a
1    b
2    c
Name: name, dtype: object

In [8]:
df[['name','age']]

  name  age
0    a   20
1    b   40
2    c   30

In [9]:
df.iloc[0] #

name      a
age      20
score     1
Name: 0, dtype: object

In [10]:
#slicing
df[0:2]

  name  age  score
0    a   20      1
1    b   40      2

In [11]:
df[0:1]

  name  age  score
0    a   20      1

In [12]:
df[df['age']>30]

  name  age  score
1    b   40      2

In [15]:
df[(df["age"]>30) & (df["score"]>1)]

  name  age  score
1    b   40      2

In [16]:
df.isnull()

    name    age  score
0  False  False  False
1  False  False  False
2  False  False  False

In [17]:
df.dropna()

  name  age  score
0    a   20      1
1    b   40      2
2    c   30      3

In [25]:
df.rename(columns={'name':'Full name'},inplace=True)
df

  Full name  age  score
0         a   20      1
1         b   40      2
2         c   30      3

In [26]:
df.replace('a','mishika',inplace=True)
df

  Full name  age  score
0   mishika   20      1
1         b   40      2
2         c   30      3

In [28]:
df['age'].mean()

np.float64(30.0)

In [29]:
df['age'].sum()

np.int64(90)

In [30]:
df['age'].max()

40

In [31]:
df['age'].min()

20

In [32]:
df.sort_values(by='age') #default ascending

  Full name  age  score
0   mishika   20      1
2         c   30      3
1         b   40      2

In [33]:
df.sort_values(by='age',ascending=False)

  Full name  age  score
1         b   40      2
2         c   30      3
0   mishika   20      1

In [39]:
df.groupby('Full name')['age'].mean()

Full name
b          40.0
c          30.0
mishika    20.0
Name: age, dtype: float64