In [ ]:
#pandas-used for data analysis and data manipulation such as data cleaning or filtering

In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [4]:
s=pd.Series([10,20,30]) #self indexed
print(s)

0    10
1    20
2    30
dtype: int64

In [5]:
s=pd.Series([10,20,30], index=['a','b','c']) 
print(s)

a    10
b    20
c    30
dtype: int64

In [7]:
data={"Name":['mishika','mishi'],'age':[20,20]}
df=pd.DataFrame(data)
df

      Name  age
0  mishika   20
1    mishi   20

In [9]:
data={'name' :["a","b","c"],'age':[20,40,30],'score':[1,2,3]}
df=pd.DataFrame(data)
df

  name  age  score
0    a   20      1
1    b   40      2
2    c   30      3

In [ ]:
#series=1d , dataframe=2d 
#dataframe from lit of dictionary